spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  # Kafka disabled for testing
  # kafka:
  #   bootstrap-servers: localhost:9092

server:
  port: 8080

service:
  recommend: http://localhost:5000
  profile: http://localhost:8081

# Kafka topics disabled
# kafka:
#   topics:
#     product-approval: product.approval 