spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: ${DB_PASSWORD:xxxx}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
        spring.json.trusted.packages: "*"

server:
  port: 8080

# AWS Configuration
aws:
  access-key: ${AWS_ACCESS_KEY:xxxx}
  secret-key: ${AWS_SECRET_KEY:xxxx}
  bucket-name: ${AWS_BUCKET_NAME:xxxx}
  region: ${AWS_REGION:xxxx}

service:
  recommend: http://localhost:5000
  profile: http://localhost:8081

kafka:
  topics:
    product-approval: product.approval
