version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: order_postgres
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    volumes:
      - order_pgdata:/var/lib/postgresql/data
volumes:
  order_pgdata: 