version: '3.8'

services:
  user-service:
    build: .
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@mongodb:27018/user?authSource=admin
      IDP_URL: http://keycloak:8080
      IDP_CLIENT_ID: test
      IDP_CLIENT_SECRET: rPhbE1REFFtfKTHSY8LmE1lGOiSeWiYy
    depends_on:
      - mongodb
      - keycloak
    restart: unless-stopped

  mongodb:
    image: mongo:7
    container_name: mongodb-user
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: user
    ports:
      - "27018:27017"
    volumes:
      - mongodb_user_data:/data/db
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.0
    container_name: keycloak-auth
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    ports:
      - "8180:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    depends_on:
      - postgres
    command: start-dev
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: postgres-keycloak
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  mongodb_user_data:
  keycloak_data:
  postgres_data: 