version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-products
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:admin}
    ports:
      - "5433:5432"
    volumes:
      - postgres_products_data:/var/lib/postgresql/data
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: elasticsearch-products
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_products_data:/usr/share/elasticsearch/data
    restart: unless-stopped
    networks:
      - elastic

  kibana:
    image: kibana:8.11.0
    container_name: kibana-products
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: unless-stopped
    networks:
      - elastic

volumes:
  postgres_products_data:
  elasticsearch_products_data:

networks:
  elastic:
    driver: bridge 