server:
    port: 8888

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: http://localhost:8080
              predicates:
                - Path=/api/products/**
              filters:
                - StripPrefix=2
            - id: profile-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/profile/**
              filters:
                - StripPrefix=2
            - id: auth-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=1
            - id: cart-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/carts/**
              filters:
                - StripPrefix=1
            - id: recommend-service
              uri: http://localhost:5000
              predicates:
                - Path=/api/recommend/**
              filters:
                - StripPrefix=2
            - id: chat-service
              uri: http://localhost:8084
              predicates:
                - Path=/api/chat/**
              filters:
                - StripPrefix=2
            - id: order-service
              uri: http://localhost:8085
              predicates:
                - Path=/api/order/**
              filters:
                - StripPrefix=2
            - id: order-service
              uri: http://localhost:8086
              predicates:
                - Path=/api/notifications/**
              filters:
                - StripPrefix=2
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/kltn
