server:
    port: 8888

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: http://localhost:8080
              predicates:
                - Path=/api/products/**
              filters:
                - StripPrefix=1
