spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://admin:${MONGODB_PASSWORD:xxxx}@localhost:27018/user?authSource=admin
server:
  port: 8081

idp:
  url: ${KEYCLOAK_URL:xxxx}
  client-id: ${KEYCLOAK_CLIENT_ID:xxxx}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:xxxx}

service:
  order-service: http://localhost:8085
