server:
  port: 8086

spring:
  application:
    name: notification-service
  
  # Disable FreeMarker auto-configuration if not needed
  freemarker:
    enabled: false
  
  # Enable Thymeleaf for email templates
  thymeleaf:
    enabled: true
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  
  datasource:
    url: jdbc:postgresql://localhost:5435/notification_db
    username: postgres
    password: ${DB_PASSWORD:xxxx}
    driver-class-name: org.postgresql.Driver
  
  jpa:  
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME:xxxx}
    password: ${GMAIL_PASSWORD:xxxx}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service-group
      auto-offset-reset: latest  # Chỉ đọc messages mới
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

# Notification Service Configuration
notification:
  email:
    from: noreply@yourdomain.com
    retry-count: 3
    retry-delay: 5000
  
  sms:
    provider: twilio
    retry-count: 3
    retry-delay: 3000
  
  push:
    provider: firebase
    retry-count: 3
    retry-delay: 2000
  
  kafka:
    topics:
      email: notification.email
      sms: notification.sms
      push: notification.push
      inapp: notification.inapp
      retry: notification.retry

# External Services
service:
  user: http://localhost:8081
  order: http://localhost:8085
  product: http://localhost:8080

# Feign Client Configuration
feign:
  client:
    config:
      products-service:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL
  compression:
    request:
      enabled: true
    response:
      enabled: true

# Logging
logging:
  level:
    org.example.notification_service: DEBUG
    org.springframework.kafka: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.example.notification_service.client.ProductsClient: DEBUG
    feign: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always 
